version: "3.7"

services:
  runblue-db:
    image: postgres:13.1
    restart: unless-stopped
    networks:
      - runblue_bridge
    environment:
      POSTGRES_DB: runblue
      POSTGRES_USER: runblue_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    expose:
      # Opens port 5432 on the container
      - "5432"
      # Where our data will be persisted
    volumes:
      - ./sql/:/docker-entrypoint-initdb.d/
      - runbluedb:/var/lib/postgres

  runblue-api:
    build: .
    restart: unless-stopped
    networks:
      - runblue_bridge
    environment:
      POSTGRES_HOST: runblue-db
    ports:
      - "8080:8080"
    expose:
      - "8080"

  adminer:
    image: adminer
    restart: unless-stopped
    networks:
      - runblue_bridge
    environment:
      ADMINER_DEFAULT_SERVER: runblue-db
      ADMINER_DESIGN: nette
    ports:
      - "5000:8080"
    expose:
      - "5000"

networks:
  runblue_bridge:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.name: runblue_bridge

volumes:
  runbluedb: null
