PRAGMA foreign_keys = ON;

CREATE TABLE users(
  username VARCHAR(20) PRIMARY KEY,
  password VARCHAR(256),
  created DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE posts(
  postid INTEGER PRIMARY KEY AUTOINCREMENT,
  filename VARCHAR(64),
  owner VARCHAR(20),
  caption VARCHAR(20),
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (owner) REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE workout(
  workoutid INTEGER PRIMARY KEY AUTOINCREMENT,
  time INTEGER,
  distance VARCHAR(20),
  owner VARCHAR(20),
  postid INTEGER,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (owner) REFERENCES users(username) ON UPDATE CASCADE ON DELETE CASCADE
  FOREIGN KEY (postid) REFERENCES posts(postid) ON UPDATE CASCADE ON DELETE CASCADE
);

CREATE TABLE routes(
  routeid INTEGER PRIMARY KEY AUTOINCREMENT,
  workoutid INTEGER,
  created DATETIME DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (workoutid) REFERENCES workout(workoutid) ON UPDATE CASCADE ON DELETE CASCADE
);


